---
- hosts: python_servers
  become: yes
  tasks:
    - name: Ensure system is up-to-date on Debian-based systems
      apt:
        update_cache: yes
        upgrade: dist
      when: ansible_facts['os_family'] == 'Debian'

    - name: Ensure system is up-to-date on RedHat-based systems
      yum:
        name: '*'
        state: latest
      when: ansible_facts['os_family'] == 'RedHat'

    - name: Install required packages on Debian-based systems
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - python3
        - python3-pip
        - git
      when: ansible_facts['os_family'] == 'Debian'

    - name: Install required packages on RedHat-based systems
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - python3
        - python3-pip
        - git
      when: ansible_facts['os_family'] == 'RedHat'

    - name: Clone the repository
      git:
        repo: 'https://github.com/LuisJoseSanchez/hola-mundo-python.git'
        dest: "/home/{{ ansible_user }}/hola-mundo-python"
        update: yes

  handlers:
    - name: Dependencies installed
      debug:
        msg: "Python dependencies have been installed successfully."

